name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@v3.0.0
        with:
          sonarqube-token: ${{ secrets.SONARQUBE_TOKEN }}
          sonarqube-url: https://sonarqube.web.musketeers.dev
          scanner-mode: CLI
          cli-args: --languages=python -- sources=. --include=**/*.py

      
          
