name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to SonarQube
        uses: sonarqube-community/sonarqube-github-action@v1
        with:
          sonarqube-token: ${{ secrets.SONARQUBE_TOKEN }}
          sonarqube-url: https://sonarqube.web.musketeers.dev

      - name: Run SonarQube Analysis
        uses: sonarqube-community/sonarqube-github-action@v1
        with:
          sonarqube-token: ${{ secrets.SONARQUBE_TOKEN }}
          sonarqube-url: https://sonarqube.web.musketeers.dev
          scanner-mode: CLI
          cli-args: --languages=python -- sources=. --include=**/*.py

      - name: Upload SonarQube Report
        uses: sonarqube-community/sonarqube-github-action@v1
        with:
          sonarqube-token: ${{ secrets.SONARQUBE_TOKEN }}
          sonarqube-url: https://sonarqube.web.musketeers.dev
          report-path: ./sonarqube-report.json
