name: Python SonarQube Scan

on:
  push:
    branches: [ main ]

jobs:
  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarqube.web.musketeers.dev
        with:
          args: >
            -Dsonar.projectKey=sonarqube
            -Dsonar.sources=.
            -Dsonar.python.version=3
          
         

      
          
